name: Deploy Wasm tune.rs on GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Install cargo fmt
        run: rustup component add rustfmt

      - name: Format test
        run: cargo fmt --all -- --check

      - name: Cargo check tuners_wasm
        run: cargo check -p tuners_wasm --target wasm32-unknown-unknown

      # - name: Cargo check tuners_native
      #   run: cargo check -p tuners_ native

      - name: Cargo check cli
        run: cargo check -p cli

      - name: Cargo check dsp
        run: cargo check -p dsp

        #cfg pour audio et gui ? 

      - name: Install Clippy
        run: rustup component add clippy

      - name: Clippy tuners_wasm
        run: cargo clippy -p tuners_wasm --target wasm32-unknown-unknown -- -D warnings

      - name: Clippy tuners_native
        run: cargo clippy -p tuners_native 

      - name: Clippy cli
        run: cargo clippy -p cli 

      - name: Clippy dsp
        run: cargo clippy -p dsp 

        #cfg for gui and audio ?

      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Build
        run: trunk build --release --public-url "/${{ github.event.repository.name }}/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
