[package]
name = "dsp"
version = "0.1.0"
edition = "2024"

[dependencies]
audio = { version = "0.1.0", path = "../audio" }
rtrb = "0.3.2"
web-sys = "0.3"
clap = { version = "4.5.53", features = ["derive"] }

[lib]
name = "dsp"
path = "src/lib.rs"
